#!/bin/bash
#
# wrapper for leandvb-GUI
# is checks and sets the max pipe size
# 
# TODO incorporate this funtionallity in leandvb-GUI

max_pipe_size=32000000
pipe_size=$(cat /proc/sys/fs/pipe-max-size)

if [ $pipe_size -lt $max_pipe_size ]; then
	echo "max pipe size is $pipe_size, will be set to $max_pipe_size"
	sudo bash -c "echo "$max_pipe_size" > /proc/sys/fs/pipe-max-size"
	pipe_size=$(cat /proc/sys/fs/pipe-max-size)
	echo "max pipe size is now $pipe_size"
else
	echo "max pipe size is $pipe_size, this is ok"
fi

#start the program
python leandvb-GUI.py


